- name: 'Media API'
  uriPattern: 'neos/graphql/<GraphQLSubroutes>'
  subRoutes:
    'GraphQLSubroutes':
      package: 't3n.GraphQL'
      variables:
        'endpoint': 'media-assets'

- name: 'Media GraphQL API'
  uriPattern: 'neos/graphql2'
  defaults:
    '@package': 'Flowpack.Media.Ui'
    '@controller': 'Media'
    '@format': 'json'
    '@action': 'query'
  httpMethods: ['GET', 'POST']
